CREATE TABLE IF NOT EXISTS n_chart_carriage_param (
    report_time TIMESTAMP NOT NULL,
    dvc_train_no INTEGER NOT NULL,
    dvc_carriage_no INTEGER NOT NULL,
    吸气压力_U11 DOUBLE PRECISION,
    吸气压力_U12 DOUBLE PRECISION,
    吸气压力_U21 DOUBLE PRECISION,
    吸气压力_U22 DOUBLE PRECISION,
    高压压力_U11 DOUBLE PRECISION,
    高压压力_U12 DOUBLE PRECISION,
    高压压力_U21 DOUBLE PRECISION,
    高压压力_U22 DOUBLE PRECISION,
    新风温度_U1 DOUBLE PRECISION,
    新风温度_U2 DOUBLE PRECISION,
    回风温度_U1 DOUBLE PRECISION,
    回风温度_U2 DOUBLE PRECISION,
    送风温度_U11 DOUBLE PRECISION,
    送风温度_U12 DOUBLE PRECISION,
    送风温度_U21 DOUBLE PRECISION,
    送风温度_U22 DOUBLE PRECISION,
    送风温度_U1 DOUBLE PRECISION,
    送风温度_U2 DOUBLE PRECISION,
    CO2_U1 DOUBLE PRECISION,
    CO2_U2 DOUBLE PRECISION,
    湿度_U1 DOUBLE PRECISION,
    湿度_U2 DOUBLE PRECISION,
    车厢温度_1 DOUBLE PRECISION,
    车厢温度_2 DOUBLE PRECISION,
    车厢湿度_1 DOUBLE PRECISION,
    车厢湿度_2 DOUBLE PRECISION,
    PRIMARY KEY (report_time)
);

SELECT create_hypertable('n_chart_carriage_param', 'report_time', chunk_time_interval => INTERVAL '1 day', if_not_exists => TRUE);